### ISSUE TITLE
[Velocity] Error on Offline mode

### ISSUE THREAD

**Issue by iSnakeBuzz** [tebexio/Tebex-Minecraft#10]
This seems like the information from the API is not the expected in the plugin.

```shell
[17:48:59 WARN] [io.tebex.plugin.TebexPlugin]: Failed to get online commands: java.lang.NullPointerException: Cannot invoke "String.replaceFirst(String, String)" because "id" is null
[17:48:59 ERROR]: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "String.replaceFirst(String, String)" because "id" is null
[17:48:59 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[17:48:59 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[17:48:59 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
[17:48:59 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[17:48:59 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
[17:48:59 ERROR]:       at io.tebex.sdk.request.TebexRequest$1.onResponse(TebexRequest.java:120)
[17:48:59 ERROR]:       at net.analyse.plugin.libs.okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
[17:48:59 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:48:59 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:48:59 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:840)
[17:48:59 ERROR]: Caused by: java.lang.NullPointerException: Cannot invoke "String.replaceFirst(String, String)" because "id" is null
[17:48:59 ERROR]:       at io.tebex.sdk.util.UUIDUtil.mojangIdToJavaId(UUIDUtil.java:14)
[17:48:59 ERROR]:       at io.tebex.sdk.platform.Platform.lambda$handleOnlineCommands$4(Platform.java:193)
[17:48:59 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[17:48:59 ERROR]:       ... 7 more
```

**Comment by WildBamaBoy** [comment]
There's issues here looking up the appropriate player ID. Are you running your server in offline mode by chance?

**Comment by iSnakeBuzz** [comment]
> There's issues here looking up the appropriate player ID. Are you running your server in offline mode by chance?

Yep
