### ISSUE TITLE
[All Platforms] Commands cannot be executed for servers in Offline mode

### ISSUE THREAD

**Issue by Gilthunderx** [tebexio/Tebex-Minecraft#17]
```
01:43:23 WARN]: [Tebex] Failed to get online commands: java.lang.NullPointerException: Cannot invoke "String.replaceFirst(String, String)" because "id" is null
[01:43:23 WARN]: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "String.replaceFirst(String, String)" because "id" is null
[01:43:23 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[01:43:23 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[01:43:23 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
[01:43:23 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[01:43:23 WARN]:        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
[01:43:23 WARN]:        at tebex-bukkit-2.0.1.jar//io.tebex.sdk.request.TebexRequest$1.onResponse(TebexRequest.java:120)
[01:43:23 WARN]:        at tebex-bukkit-2.0.1.jar//io.tebex.plugin.libs.okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
[01:43:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[01:43:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[01:43:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[01:43:23 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "String.replaceFirst(String, String)" because "id" is null
[01:43:23 WARN]:        at tebex-bukkit-2.0.1.jar//io.tebex.sdk.util.UUIDUtil.mojangIdToJavaId(UUIDUtil.java:14)
[01:43:23 WARN]:        at tebex-bukkit-2.0.1.jar//io.tebex.sdk.platform.Platform.lambda$handleOnlineCommands$4(Platform.java:195)
[01:43:23 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[01:43:23 WARN]:        ... 7 more
```

Hello i need help, my store is not doing commands to my server.

**Comment by WildBamaBoy** [comment]
We've seen this occur when the server is running in offline mode. Can you confirm - is the server running in offline mode?

**Comment by Gilthunderx** [comment]
Yes offline mode since we are running a bungeecord

**Comment by WildBamaBoy** [comment]
Thank you for the info! We'll take a look at this ASAP.

**Comment by l3nnartt** [comment]
our Server is in online mode and the id got not replaced, not sure if this is related to that issue?
The email support told me end of the next week there will be a release
