### ISSUE TITLE
[Minecraft Offline/Bedrock] Error when the commands executes

### ISSUE THREAD

**Issue by MixtoDesigns** [tebexio/Tebex-Minecraft#26]
Spigot 1.18.2

Tebex 2.0.2

Error:

[18:47:46 WARN]: [Tebex] Task #20454 for Tebex v2.0.2 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
at java.lang.String.replace(String.java:2961) ~[?:?]
at io.tebex.sdk.obj.QueuedCommand.getParsedCommand(QueuedCommand.java:46) ~[tebex-bukkit-2.0.2.jar:?]
at io.tebex.sdk.platform.Platform.lambda$null$7(Platform.java:270) ~[tebex-bukkit-2.0.2.jar:?]
at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1534) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1458) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1228) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:318) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by usernamegithu210** [comment]
I'm having the same issue.
