### ISSUE TITLE
Tebex throwing errors when the server close.

### ISSUE THREAD

**Issue by GeoGb1** [tebexio/Tebex-Minecraft#36]
- Server type: Paper
- Server Version: 1.20.4
- Tebex plugin version: 2.0.3
- Whenever i close my server. it takes a while to go offline and I also get the errors below. I do not know if the close time is related to the tebex errors.
```
[16:44:06] [Server thread/WARN]: Exception in thread "OkHttp TaskRunner" java.lang.IllegalStateException: zip file closed
--
959 | [16:44:06] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:840)
960 | [16:44:06] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:339)
961 | [16:44:06] [Server thread/WARN]: 	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:517)
962 | [16:44:06] [Server thread/WARN]: 	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:472)
963 | [16:44:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)
964 | [16:44:06] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
965 | [16:44:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
966 | [16:44:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
967 | [16:44:06] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
968 | [16:44:06] [Server thread/WARN]: 	at tebex-bukkit-2.0.3.jar//io.tebex.plugin.libs.okhttp3.internal.http2.Http2Connection.shutdown(Http2Connection.kt:419)
969 | [16:44:06] [Server thread/WARN]: 	at tebex-bukkit-2.0.3.jar//io.tebex.plugin.libs.okhttp3.internal.http2.Http2Connection.close$okhttp(Http2Connection.kt:449)
970 | [16:44:06] [Server thread/WARN]: 	at tebex-bukkit-2.0.3.jar//io.tebex.plugin.libs.okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:627)
971 | [16:44:06] [Server thread/WARN]: 	at tebex-bukkit-2.0.3.jar//io.tebex.plugin.libs.okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
972 | [16:44:06] [Server thread/WARN]: 	at tebex-bukkit-2.0.3.jar//io.tebex.plugin.libs.okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
973 | [16:44:06] [Server thread/WARN]: 	at tebex-bukkit-2.0.3.jar//io.tebex.plugin.libs.okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
974 | [16:44:06] [Server thread/WARN]: 	at tebex-bukkit-2.0.3.jar//io.tebex.plugin.libs.okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
975 | [16:44:06] [Server thread/WARN]: 	at tebex-bukkit-2.0.3.jar//io.tebex.plugin.libs.okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
976 | [16:44:06] [Server thread/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
977 | [16:44:06] [Server thread/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
978 | [16:44:06] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by WildBamaBoy** [comment]
Hi there, a few questions:
- What other plugins are you running on the server? 
- Does this seem to happen on every restart? 
- Does it also occur if Tebex is the only loaded plugin?
