### ISSUE TITLE
Velocity UUID error

### ISSUE THREAD

**Issue by bobhenl** [tebexio/Tebex-Minecraft#37]
## Please include the following information with your report
- Server type and version (ex. Spigot 1.18.2)
- Tebex plugin version (ex. 2.0.1)
- Description of the issue with any error messages, stack traces, or relevant logs.
Velocity 3.3.0 Snapshot 360
Tebex plugin version  tebex-velocity 2.0.3

I'm getting this error:
```
[00:26:19 INFO] [io.tebex.plugin.TebexPlugin]: Connected to NAMEOFTHESERVER - Minecraft (Offline/Geyser) server.
[00:26:19 WARN] [io.tebex.plugin.TebexPlugin]: Failed to perform check: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.UUID (java.lang.String and java.util.UUID are in module java.base of loader 'bootstrap')
[00:26:19 ERROR]: java.util.concurrent.CompletionException: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.UUID (java.lang.String and java.util.UUID are in module java.base of loader 'bootstrap')
[00:26:19 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[00:26:19 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[00:26:19 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
[00:26:19 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[00:26:19 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
[00:26:19 ERROR]:       at io.tebex.sdk.request.TebexRequest$1.onResponse(TebexRequest.java:141)
[00:26:19 ERROR]:       at net.analyse.plugin.libs.okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
[00:26:19 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[00:26:19 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[00:26:19 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:840)
[00:26:19 ERROR]: Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.UUID (java.lang.String and java.util.UUID are in module java.base of loader 'bootstrap')
[00:26:19 ERROR]:       at io.tebex.plugin.TebexPlugin.getPlayer(TebexPlugin.java:265)
[00:26:19 ERROR]:       at io.tebex.plugin.TebexPlugin.isPlayerOnline(TebexPlugin.java:273)
[00:26:19 ERROR]:       at io.tebex.sdk.platform.Platform.handleOnlineCommands(Platform.java:189)
[00:26:19 ERROR]:       at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[00:26:19 ERROR]:       at io.tebex.sdk.platform.Platform.lambda$performCheck$2(Platform.java:156)
[00:26:19 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[00:26:19 ERROR]:       ... 7 more
```

**Comment by WildBamaBoy** [comment]
You will need to ensure the server is in proxy mode, see https://github.com/tebexio/Tebex-Minecraft/issues/27#issuecomment-1932432666

**Comment by bobhenl** [comment]
Even when I enable it, it keeps happening
```
[17:28:14 INFO] [io.tebex.plugin.TebexPlugin]: Connected to HeartSMP's Minehut Proxy - Minecraft (Offline/Geyser) server.
[17:28:15 WARN] [io.tebex.plugin.TebexPlugin]: Failed to perform check: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.UUID (java.lang.String and java.util.UUID are in module java.base of loader 'bootstrap')
[17:28:15 ERROR]: java.util.concurrent.CompletionException: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.UUID (java.lang.String and java.util.UUID are in module java.base of loader 'bootstrap')
[17:28:15 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[17:28:15 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[17:28:15 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
[17:28:15 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[17:28:15 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
[17:28:15 ERROR]:       at io.tebex.sdk.request.TebexRequest$1.onResponse(TebexRequest.java:141)
[17:28:15 ERROR]:       at net.analyse.plugin.libs.okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
[17:28:15 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:28:15 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:28:15 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:840)
[17:28:15 ERROR]: Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.UUID (java.lang.String and java.util.UUID are in module java.base of loader 'bootstrap')
[17:28:15 ERROR]:       at io.tebex.plugin.TebexPlugin.getPlayer(TebexPlugin.java:265)
[17:28:15 ERROR]:       at io.tebex.plugin.TebexPlugin.isPlayerOnline(TebexPlugin.java:273)
[17:28:15 ERROR]:       at io.tebex.sdk.platform.Platform.handleOnlineCommands(Platform.java:189)
[17:28:15 ERROR]:       at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[17:28:15 ERROR]:       at io.tebex.sdk.platform.Platform.lambda$performCheck$2(Platform.java:156)
[17:28:15 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[17:28:15 ERROR]:       ... 7 more
```

Current backend config:
```
# These settings are exclusive to this server.
# Do not share these credentials with anyone.
server:
  # Proxy Mode
  # If you are using BungeeCord/Velocity, set this to true.
  proxy: 'true'
```
