### ISSUE TITLE
Failed to retrieve offline commands - some commands may not have been processed.

### ISSUE THREAD

**Issue by Warzel** [tebexio/Tebex-Minecraft#64]
Server: Fabric 1.20.1
Tebex: 2.0.6

When a customer bought my product on my offline java minecraft store provided by Tebex, i get this log:
`[19:08:43] [Tebex Thread 6/INFO]: Dispatching offline command '/wanderwl add warzelous' for player 'warzelous'.
[19:08:43] [OkHttp https://plugin.tebex.io/.../WARN]: Failed to retrieve offline commands - some commands may not have been processed. java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'com.mojang.brigadier.CommandDispatcher net.minecraft.class_2168.method_54310()'
[19:08:43] [OkHttp https://plugin.tebex.io/.../WARN]: - We will try again at the next due player check.
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'com.mojang.brigadier.CommandDispatcher net.minecraft.class_2168.method_54310()'
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	at io.tebex.sdk.request.TebexRequest$1.onResponse(TebexRequest.java:141)
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	at io.tebex.plugin.libs.okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'com.mojang.brigadier.CommandDispatcher net.minecraft.class_2168.method_54310()'
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	at io.tebex.plugin.TebexPlugin.executeBlockingLater(TebexPlugin.java:242)
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	at io.tebex.sdk.platform.Platform.lambda$handleOfflineCommands$7(Platform.java:320)
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	... 7 more
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'com.mojang.brigadier.CommandDispatcher net.minecraft.class_2168.method_54310()'
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	at io.tebex.plugin.util.Multithreading.executeBlockingLater(Multithreading.java:56)
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	at io.tebex.plugin.TebexPlugin.executeBlockingLater(TebexPlugin.java:240)
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	... 9 more
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: Caused by: java.lang.NoSuchMethodError: 'com.mojang.brigadier.CommandDispatcher net.minecraft.class_2168.method_54310()'
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	at io.tebex.plugin.TebexPlugin.dispatchCommand(TebexPlugin.java:214)
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	at io.tebex.sdk.platform.Platform.lambda$null$6(Platform.java:322)
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[19:08:43] [OkHttp https://plugin.tebex.io/.../INFO]: [STDERR]: 	... 3 more
`

![image](https://github.com/user-attachments/assets/d5598ba3-1479-4c01-996b-d75d6ef64b9e)

The product is supposed to work like paid whitelist.

Please help, I've been trying to figure this out for 2 days. Thank you for any suggestions!

**Comment by WildBamaBoy** [comment]
Hey there, thanks for your report. There is a duplicate issue reported just before yours here https://github.com/tebexio/Tebex-Minecraft/issues/63

You may be able to try Fabric 1.20.4 as that is the version the plugin was specifically compiled for. However, our intent is for the plugin to work or be available for all versions. For now I will close this as a duplicate.
