### ISSUE TITLE
crash after tick loop

### ISSUE THREAD

**Issue by unnamed199cz** [tebexio/Tebex-Minecraft#68]
## Please include the following information with your report
- Server type and version Paper 1.21
- Tebex plugin version 2.0.5

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 2024-08-07 07:34:53
Description: Exception in server tick loop

java.lang.ExceptionInInitializerError
	at tebex-bukkit-2.0.5.jar//io.tebex.plugin.gui.BuyGUI.getCategoryItemBuilder(BuyGUI.java:123)
	at tebex-bukkit-2.0.5.jar//io.tebex.plugin.gui.BuyGUI.lambda$open$1(BuyGUI.java:50)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at tebex-bukkit-2.0.5.jar//io.tebex.plugin.gui.BuyGUI.open(BuyGUI.java:49)
	at tebex-bukkit-2.0.5.jar//io.tebex.plugin.command.BuyCommand.execute(BuyCommand.java:25)
	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443)
	at net.minecraft.commands.Commands.performCommand(Commands.java:350)
	at net.minecraft.commands.Commands.performCommand(Commands.java:337)
	at net.minecraft.commands.Commands.performCommand(Commands.java:332)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2147)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2121)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537)
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514)
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507)
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466)
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: dev.triumphteam.gui.components.exception.GuiException: Could not retrieve displayName nor lore field for ItemBuilder.
	at tebex-bukkit-2.0.5.jar//dev.triumphteam.gui.builder.item.BaseItemBuilder.<clinit>(BaseItemBuilder.java:85)
	... 32 more

**Comment by WildBamaBoy** [comment]
Hi there, this issue is resolved in version 2.0.6. Please update to the latest version.
